name: time_picker_sheet
description: Time picker sheet library, allows you to have beauty time picker sheet with customable design to align with your requirements.
homepage: https://github.com/yoktavian/time-picker-sheet
version: 0.0.2+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:

  uses-material-design: true